### ISSUE TITLE
So nothing good in this app

### ISSUE THREAD

**Issue by JakiHappyCity** [haskellcamargo/skype-unofficial-client#28]
For what's this app, if is web.skype.com in other app? Calling and web calling don't working, other stuffs can work and in web skype.

**Comment by Kuchiriel** [comment]
This stuffs can work, people just need to collaborate and make things happen. nw.js has many capabilities.

**Comment by gizmocodes** [comment]
I'm somewhat confused on what your asking, but heres what I'm getting. You want the client to support calls, and thats in the works. Due to legal reasons, haskell can't include direct Skype code from either an offical client nor web.skype.com. From what I saw in the commit history, parts of the open-source project Chromium (The upstream version of Google Chrome) are in the project, and I imagine they are planning on adding in the part to support extensions, such as the extension required for web.skype.com to make calls. The client is essentially a wrapper, wrapping the website into a client.

Since the bits of Chromium that are used to make plugins work is not implemented yet, thats why it can't make calls. (If you need to make calls and really don't like the default Skype for Linux client, try getting Wine and the Windows Skype or bootleg Windows.)

**Comment by Kuchiriel** [comment]
It seems kind of complicated, but may be possible.
https://github.com/nwjs/nw.js/issues/792
https://github.com/nwjs/nw.js/wiki/Third-party-browser-plugins

**Comment by JakiHappyCity** [comment]
Too stupid, for one call i (for example) need new lib (or not lib, i don't know js and other web langs). You maybe can create new client working only on SkypeAPI, which can be working on linux.

**Comment by haskellcamargo** [comment]
Plot twist: there is no Skype API.
I can't even write a crawler to fetch data without getting a lawsuit from Microsoft for that.

**Comment by gizmocodes** [comment]
Ahh, Microsoft. Not only do they spy on us (Read their license agreement, seriously), when we try to revolt we get shot down.

**Comment by Kuchiriel** [comment]
I did not know about the legal issues, i was thinking about write some crawler too. Thankfully i have read this first. Well, there is nothing we can (legallly) do. It is up to nw.js people. Anything reopen the issue.
