### ISSUE TITLE
Fedora 23 Suport

### ISSUE THREAD

**Issue by nacr** [haskellcamargo/skype-unofficial-client#45]
This is not a issue, is there a Fedora rpm install for this software?
 Or a guide?

**Comment by gizmocodes** [comment]
Why not just compile it yourself? The instructions are on the [README.md](https://github.com/haskellcamargo/skype-unofficial-client/blob/master/README.md) and are easy enough to follow. If you absolutely NEED an RPM for some odd reason, I _can_ provide one (since I'm on a [Fedora Remix](http://kororaproject.org)), but I'd need a good reason.
