### ISSUE TITLE
Deprecate in favor of ghetto-skype?

### ISSUE THREAD

**Issue by onlurking** [haskellcamargo/skype-unofficial-client#65]
We should deprecate this project in favor of [ghetto-skype](https://github.com/stanfieldr/ghetto-skype) and edit the README to send people to the other project(which is better maintained)?

What you guys think? @haskellcamargo, @Kuchiriel.

**Comment by haskellcamargo** [comment]
:white_check_mark: 
I believe so. This was a very good alternative when it all started, before Microsoft releasing an official version and better alternatives arising, like Ghetto. It also helped to inspire new projects of a web-based Skype, but its role is done. I have no more time to maintain this project because I'm very focused on @quack now. I approve.

**Comment by haskellcamargo** [comment]
What is your opinion, @Kuchiriel?

**Comment by Kuchiriel** [comment]
I agree with you both. @onlurking @haskellcamargo
